### ISSUE TITLE
mongo_dbpedia-2015-10.tar.bz2 corrupted?

### ISSUE THREAD

**Issue by schelv** [iai-group/nordlys#13]
Hi,
I am following the nordlys [installation instructions](https://nordlys.readthedocs.io/en/latest/installation.html)
The command below give some strange output
`./scripts/load_mongo_dumps.sh mongo_dbpedia-2015-10.tar.bz2`
One of the things it is saying is that the compressed file ends unexpectedly and that it perhaps is corrupted.
Can you help fix this? Or is this supposed to happen?

I've attached the full output
[script_output.txt](https://github.com/iai-group/nordlys/files/1545646/script_output.txt)

**Comment by hasibi** [comment]
Hi,
I can see in your log file that the mongo dump is stored as:
``/nordlys/tmp/mongo_dbpedia-2015-10.tar.bz2.1``
It could be that there is a damaged file in this folder.

Delete the `./nordlys/tmp` folder (or make sure it is empty), then re-run the command.

**Comment by schelv** [comment]
It worked!
Thanks for the quick response
