### ISSUE TITLE
Incorrect filename in build_indices.sh for DBPedia types index

### ISSUE THREAD

**Issue by ruteben** [iai-group/nordlys#16]
There is a mismatch between the file in the repository and the file expected in build_indices.sh when building the DBPedia types index.

The file in the repository is called `index_dbpedia-2015-10_types.config.json` while the script looks for `index_dbpedia_2015_10_types.config.json`.

My suggestion would be renaming the file to the latter to keep the format uniform.

**Comment by hasibi** [comment]
Fixed!
