### ISSUE TITLE
Rename dbpedia-2015-10 to dbpedia-2015-10_sample

### ISSUE THREAD

**Issue by kbalog** [iai-group/nordlys#27]
- Rename `data/raw-data/dbpedia-2015-10` => `data/raw-data/dbpedia-2015-10_sample`. (The two would be exactly identical structure, but the sample is part of the repo and is small.)
  - Update documentation/scripts to work with sample by default.
  - `download_all.sh` should create `data/raw-data/dbpedia-2015-10` and download the full files under that.

**Comment by ghost** [comment]
done.
